# Etapa 1: Construcción
FROM node:20 AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build --prod

#Servidor NGINX
FROM nginx:alpine

# Copia la app compilada de Angular a la carpeta que NGINX sirve
COPY --from=build /app/Proyecto3/frontend /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
