# Etapa de build de Angular
FROM node:20 as build
WORKDIR /app
COPY package*.json ./
RUN npm install -g @angular/cli
RUN npm install
COPY . .
RUN npm run build

# Etapa 2: Servidor Nginx
FROM nginx:alpine
# Elimina la configuración por defecto
RUN rm /etc/nginx/conf.d/default.conf
# Copia TU configuración personalizada
COPY nginx.conf /etc/nginx/conf.d/
# Copia los archivos construidos de Angular
COPY --from=build /app/dist/frontend/browser /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]