# Stage 1: Build the Angular application
FROM node:18 AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build --prod # Asegúrate de que este comando de build sea correcto

# Stage 2: Serve the application with Nginx
FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf

# Copia TU ARCHIVO NGINX.CONF PERSONALIZADO
COPY nginx.conf /etc/nginx/conf.d/default.conf 

# **¡ESTA ES LA LÍNEA CLAVE A CORREGIR!**
# Copia los archivos de la aplicación Angular compilados, incluyendo la subcarpeta 'browser'
COPY --from=build /app/dist/frontend/browser /usr/share/nginx/html 

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]