services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_main
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - red_proyecto3

  login-service:
    build: ./backend/login-service
    container_name: login_service
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
    networks:
      - red_proyecto3
    volumes:
      - ./archivos:/usr/src/app/archivos



  subirpdf-service:
    build: ./backend/subirPDF-service
    container_name: subir_pdf_service
    ports:
      - "3002:3002"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
    networks:
      - red_proyecto3

  frontend:
    build: ./frontend
    container_name: angular_frontend
    ports:
      - "4200:80"
    depends_on:
      - login-service
    networks:
      - red_proyecto3

volumes:
  db_data:

networks:
  red_proyecto3:
    driver: bridge
