services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_main
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  login-service:
    build: ./backend/login-service
    container_name: login_service
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=db_main
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: angular_frontend
    ports:
      - "4200:80"
    depends_on:
      - login-service

volumes:
  db_data:
