version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_main
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - red_proyecto3

  login-service:
    image: grupomfifsl/mis-servicios:login-service-latest
    container_name: login_service

    environment:
      DB_HOST: mysql_db
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: db_main
    depends_on:
      - db
    networks:
      - red_proyecto3
    volumes:
      - ./archivos:/usr/src/app/archivos

  list-service:
    image: grupomfifsl/mis-servicios:list-service-latest
    container_name: list_service
    environment:
      DB_HOST: mysql_db
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: db_main
    depends_on:
      - db
    networks:
      - red_proyecto3
    volumes:
      - ./archivos:/usr/src/app/archivos

  upload-service:
    image: grupomfifsl/mis-servicios:upload-service-latest
    container_name: upload_service
    environment:
      DB_HOST: mysql_db
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: db_main
    depends_on:
      - db
    networks:
      - red_proyecto3
    volumes:
      - ./archivos:/usr/src/app/archivos

  searchp-service:
    image: grupomfifsl/mis-servicios:searchp-service-latest
    container_name: searchp_service
    environment:
      DB_HOST: mysql_db
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: db_main
    depends_on:
      - db
    networks:
      - red_proyecto3
    volumes:
      - ./archivos:/usr/src/app/archivos

  nginx:
    build:
      context: ./nginx 
      dockerfile: Dockerfile
    image: grupomfifsl/mis-servicios:nginx-frontend-latest 
    container_name: nginx_proxy
    ports:
      - "8008:80" 
    depends_on:
      - login-service
      - list-service
      - upload-service
      - searchp-service
    networks:
      - red_proyecto3


  frontend:
    image: grupomfifsl/mis-servicios:frontend-service-latest
    container_name: angular_frontend

    depends_on:
      - login-service 
    networks:
      - red_proyecto3


  prometheus:
    image: prom/prometheus:latest
    ports:
      - "50001:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - red_proyecto3

  grafana:
    image: grafana/grafana:latest
    ports:
      - "50002:3009"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_SERVER_HTTP_PORT=3009
    depends_on:
      - prometheus
    networks:
      - red_proyecto3

volumes:
  db_data:
  grafana-storage:

networks:
  red_proyecto3:
    external: true