version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_main
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - red_proyecto3

  login-service:
    build: ./backend/login-service
    container_name: login_service
    ports:
      - "50000:3000" 
    environment:
      DB_HOST: db 
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: db_main
    depends_on:
      - db
    networks:
      - red_proyecto3
    volumes:
      - ./archivos:/usr/src/app/archivos

  frontend:
    build: ./frontend
    container_name: angular_frontend
    ports:
      - "8008:80" 
    depends_on:
      - login-service 
    networks:
      - red_proyecto3

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - red_proyecto3

  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123 
    depends_on:
      - prometheus
    networks:
      - red_proyecto3

volumes:
  db_data:

networks:
  red_proyecto3:
    driver: bridge