name: CD a Pacheco (Desde Main)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  packages: write
  contents: read

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

jobs:
  check-paths:
    runs-on: ubuntu-latest
    outputs:
      login: ${{ steps.filter.outputs.login }}
      frontend: ${{ steps.filter.outputs.frontend }}
      list: ${{ steps.filter.outputs.list }}
      upload: ${{ steps.filter.outputs.upload }}
      searchp: ${{ steps.filter.outputs.searchp }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            login:
              - 'backend/login-service/**'
            frontend:
              - 'frontend/**'
              - 'nginx/**' # Añadir 'nginx/**' para que los cambios en Nginx también disparen el despliegue del frontend/Nginx
            list:
              - 'backend/list-service/**'
            upload:
              - 'backend/upload-service/**'
            searchp:
              - 'backend/searchp-service/**'

  deploy-login-service:
    needs: check-paths
    if: needs.check-paths.outputs.login == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t ${{ secrets.DOCKER_USER }}/mis-servicios:login-service-latest ./backend/login-service
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - run: docker push ${{ secrets.DOCKER_USER }}/mis-servicios:login-service-latest
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
            FILE="/home/sergiolara2101/proyecto-final-v1/docker-compose.yml"
            docker-compose -f $FILE stop login-service || true
            docker-compose -f $FILE rm -f login-service || true
            docker ps -aq -f name=login_service | xargs docker rm -f || true
            docker-compose -f $FILE pull login-service
            docker-compose -f $FILE up -d --remove-orphans login-service

  # Este job ahora construirá la aplicación Angular y luego la imagen de Nginx con el frontend
  deploy-nginx-with-frontend: # Renombrado para mayor claridad
    needs: check-paths
    if: needs.check-paths.outputs.frontend == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Construir la aplicación Angular
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Asegúrate de que esta versión coincida con la de tu proyecto Angular
      - name: Install Angular dependencies
        run: npm install
        working-directory: ./frontend
      - name: Build Angular application
        # Compila Angular y coloca la salida en la carpeta 'nginx/app/dist'
        # que será copiada por el Dockerfile de Nginx.
        run: npm run build -- --output-path ../nginx/app/dist
        working-directory: ./frontend

      # 2. Construir la imagen de Nginx con el frontend
      - name: Build Nginx with Frontend image
        run: docker build -t ${{ secrets.DOCKER_USER }}/mis-servicios:nginx-frontend-latest ./nginx # Construye la imagen personalizada de Nginx

      # 3. Iniciar sesión y empujar la imagen de Nginx
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push Nginx with Frontend image
        run: docker push ${{ secrets.DOCKER_USER }}/mis-servicios:nginx-frontend-latest

      # 4. Desplegar en el servidor remoto (detener, remover, pull y levantar Nginx)
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
            FILE="/home/sergiolara2101/proyecto-final-v1/docker-compose.yml"
            # Detener y remover el contenedor Nginx existente
            docker-compose -f $FILE stop nginx || true
            docker-compose -f $FILE rm -f nginx || true
            docker ps -aq -f name=nginx_proxy | xargs docker rm -f || true
            # Pull de la nueva imagen personalizada de Nginx
            docker-compose -f $FILE pull nginx
            # Levantar solo el servicio Nginx (otros servicios se manejan en sus propios deploys)
            docker-compose -f $FILE up -d --remove-orphans nginx

  # Los demás jobs de despliegue de servicios de backend (list, upload, searchp)
  # no necesitan cambios, ya que su configuración de red interna sigue siendo la misma.

  deploy-list-service:
    needs: check-paths
    if: needs.check-paths.outputs.list == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t ${{ secrets.DOCKER_USER }}/mis-servicios:list-service-latest ./backend/list-service
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - run: docker push ${{ secrets.DOCKER_USER }}/mis-servicios:list-service-latest
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
            FILE="/home/sergiolara2101/proyecto-final-v1/docker-compose.yml"
            docker-compose -f $FILE stop list-service || true
            docker-compose -f $FILE rm -f list-service || true
            docker ps -aq -f name=list_service | xargs docker rm -f || true
            docker-compose -f $FILE pull list-service
            docker-compose -f $FILE up -d --remove-orphans list-service

  deploy-upload-service:
    needs: check-paths
    if: needs.check-paths.outputs.upload == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t ${{ secrets.DOCKER_USER }}/mis-servicios:upload-service-latest ./backend/upload-service
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - run: docker push ${{ secrets.DOCKER_USER }}/mis-servicios:upload-service-latest
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
            FILE="/home/sergiolara2101/proyecto-final-v1/docker-compose.yml"
            docker-compose -f $FILE stop upload-service || true
            docker-compose -f $FILE rm -f upload-service || true
            docker ps -aq -f name=upload_service | xargs docker rm -f || true
            docker-compose -f $FILE pull upload-service
            docker-compose -f $FILE up -d --remove-orphans upload-service

  deploy-searchp-service:
    needs: check-paths
    if: needs.check-paths.outputs.searchp == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t ${{ secrets.DOCKER_USER }}/mis-servicios:searchp-service-latest ./backend/searchp-service
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - run: docker push ${{ secrets.DOCKER_USER }}/mis-servicios:searchp-service-latest
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
            FILE="/home/sergiolara2101/proyecto-final-v1/docker-compose.yml"
            docker-compose -f $FILE stop searchp-service || true
            docker-compose -f $FILE rm -f searchp-service || true
            docker ps -aq -f name=searchp_service | xargs docker rm -f || true
            docker-compose -f $FILE pull searchp-service
            docker-compose -f $FILE up -d --remove-orphans searchp-service