name: test-proyect

run-name: Test N.º${{ github.run_number }} hecho por ${{ github.actor }}
on:
  push:
    branches:
      - main

jobs:
  # Tests unitarios  de Backend-Service
  unit-test-login-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/login-service
    steps:
      - name: 💻Checkout
        uses: actions/checkout@v3

      - name: 🛠️Instalar dependecias
        run: npm install

      - name: 👾Test
        run: npm test

  # Pruebas de integración con todos los servicios dockerizados
  docker-up-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Levantar contenedores en segundo plano
        run: docker compose up -d

      - name: Esperar a que MySQL esté listo
        run: |
          for i in {1..15}; do
            if docker exec mysql_db mysqladmin ping -uroot -p1234 --silent; then
              echo "✅ MySQL listo"
              break
            fi
            echo "⏳ Esperando a MySQL..."
            sleep 2
          done

      - name: Esperar logs de login-service con conexión establecida
        run: |
          for i in {1..15}; do
            logs=$(docker logs login_service 2>&1)
            if echo "$logs" | grep -q "Conexión establecida con la base de datos"; then
              echo "✅ Login-service conectado a la base de datos"
              exit 0
            fi
            echo "⏳ Esperando conexión desde login-service..."
            sleep 2
          done
          echo "❌ No se detectó conexión en los logs"
          docker compose logs
          exit 1

      - name: Finalizar contenedores
        run: docker compose down